added n function to do basic nnn mamanagement; doens't open with preview or hiden files turned on

diff --git a/executable_dot_functions b/executable_dot_functions
--- a/executable_dot_functions
+++ b/executable_dot_functions
@@ -279,7 +279,28 @@ nn(){
         rm -f -- "$NNN_TMPFILE" > /dev/null
     }
 }
+n(){
+# Block nesting of nnn in subshells
+    [ "${NNNLVL:-0}" -eq 0 ] || {
+        echo "nnn is already running"
+        return
+    }
+    if [ -z "$EDITOR" ]; then
+        EDITOR=nano
+    fi
+    #trap cleanup_panes EXIT
+    #cleanup_panes
 
+    NNN_FIFO="$(mktemp --suffix=-nnn -u)"
+    export NNN_FIFO
+    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
+    (umask 077; mkfifo "$NNN_FIFO")
+    command nnn -E "$@"
+    [ ! -f "$NNN_TMPFILE" ] || {
+        . "$NNN_TMPFILE"
+        rm -f -- "$NNN_TMPFILE" > /dev/null
+    }
+}
 # Tmux pane management setup
 panes_cleanup() {
     if [ -n "$TMUX" ]; then
